sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks

env:
  global:
  - secure: "bt9sQ7T/HGQ+wfkFi4yhQ0kCzdERtv3wOp0piiyz5XmLqRFG3cFplAqOVpBVHHa3DEnRHdTxNmVR+CRImuH2ULMos8B+EyTAMG8PnFI5cNveEtmODMP44b+jtSayXA5zSaZBJ5qHAnJWvVfZ2mLl02bt3tkh82Yr/4+YtgCboIEI7ZD2bdoDqzkP7zcM9xZn+ohcj6dAsSCcyk7XRRSZuuRHLhcZOkV+cKN8uTcxRoftOR2SLpJmGvZ/5XAo0AVyI5ILakq0wFaNI4F79yrP5tMiKqNOgPdw8bCjygelfj5TXilNLjmkzfEfXT2Fi7Jf3+PvpOM/nz2CpxRlB70DWJCaoP5InWGoLSFBEFRp1Ff5eyTQwMinIxW+FzLcGFXtPdrE6VwaUFSy8x057yKC3t4AoVijQ4QPt8w8WEpcOiKRTbpsN8mqBWoNfLrksB1rbgYDwMemwW+8CkDyDTNWoflbVOzbMtitMjpsA6tZtDkdWZ9ThPrucm9kCS4lVh3iJgEvbRx7kRK37mnE/oiJwre0qKy/USGrEWHwFbEDtCVzUV/Pu27D81hgeldcE9DFA5JyYWl+gMteJIx1cUcWZkr8MAqlxp1BaP2zJgZxTWnTumIb3bXvayoLVPLIzAcPkxyVkIhudMuRWJPh0YUBq1A9z18b5DTKNKeozwLr6/g="
  - secure: "nlHrCIzPfGJzWDjEl9xGoM2yZe33KmoUzON9RXKPiaGt9xdhbhpeV5uCwEc70LuPZdBEfk7TznyiPXwHxfa7JF2x6VEWVmZhbIbQPxoFUCIsAAiUkkFwxXltEu9u4BKF4aEFnsMIlyYpB0mJjGRyxwUDaAd5UTzvqw6PYpoI6CS3NjR1Mou2oGgxitT0ozmOHx9X8lkON+r4Z7iLnn1uJBMBiaRSPXn2HdSFDapyDr2X/sdNC8FLOimwHCIqtQjTxUSWUULSQB1oV7bhWpqoivhktagPe+lodJis7/kFxPnaStJ3q/5/lRfo73HcK8U26NnFiDHrEZof9ug/uYfXE8vOJszcCAvPvX5pxBxJc2jdzQqgJQk2Q22UKKMNotQ8IzzdTLNEdGTUEsw1XXHbQ6YeR3k+tYJZHYxWqNnE599RgCBbWfmrNLgxvoluvwndQ0xfJVpt8IG3mdU8VNanNLGPU//5O9AxEhkJxRvfi0bgkBXy0RtghpvUv42xapQPF7FrVUe/eLjrsh4euoRsV9hhIqEDUlGPuwxQpWqL5Cdc4wGhXdsFUYHwkR5LmlEd7kzF+SmhfiaEF3Afzw+fD5z5w2kcXVb+6rQ7nJ8Ir9EYblw9+U4pJIl0gmEC34Nc/Zp1WBN/X91j5RKzAlK+wMFpZ6yWLN5YIscczTNgBwo="
  - secure: "qJu4IQXrrJA2H7UR7ExuyvqXMnfByOWrUrs2y5ktguqDiZ2zgDMCSSNDYme9JeOwxisHEeT/GCtlDxGslfGbrMk5jdG1u6GfsdAbx7K0f0iDkJihlPKBaUrP5b45MKkRaeE0mEYagZFkx4SHXPqL1fVqlgJBG7vPnBLhGYj6xX4Osj8E7dvBQc2cwoBwD3RnQTg4f9ewRWJMD4HDQ+vKZOM8TcKlDP05zBkbSxt+L0oimWvZEeXJ4AVmw/60Epg5UKkCWdNJd0q49DOTG3pKU6GJn+ZM02+DdsZMZHaQxc95uT954oeA4Un4Bjl0Eub3v2EU/e3OhK12HMRhIXUMAFEVG32kOTrEp5DfWySuQopW7dHJTh4IfIJNNjLRUjI7ydTrpAnXKzVamS3JKOzsiFgH0zVCD4CvioFvjoiKwrTcG2fXJttxgm68uJ7pPpqXPwuANsYNs8NNzOXaFIf5oJC3zqjkYvbLSvnt69RYWAA6fGeci2TyDnGx8nPCLhum4/UmGzABywuWurjbYaMTggZXjhwLwJqtntpdgiez6d9UkVZV+thQAEN1mUcz29mJw45L9oRN97h8EunYlDNUF3IP0BXa6V+gKIUE17+7wZQ0K+u7ipeyTsO1nRVVm3NRFOlDzKYPwqcQAMre4V5T/jAn7DgjaQK7Sac5x0fMepA="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
